name: Unit Test With Coverage
on: [pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.203
    - name: Restore dependencies
      run: dotnet restore Library/Library.sln
    - name: Build
      run: dotnet build --no-restore Library/Library.sln
    - name: Test
      run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal Library/LibraryProjectCodeTests
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: Library/LibraryProjectCodeTests/TestResults/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: c624dfd2c4063c437d1857ce3478eac2
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"